### PR TITLE
Create lesson4.py

### PR DESCRIPTION
**Pull request by JosephPobega**
hey Mikey, Im not done with the lesson yet, but every time I run what I have so far, it keeps saying "Expected an intended block."

### CODE REVIEW

**Comment by Pobega** [comment]
You need to indent the code under the "for" section

**Comment by Pobega** [comment]
@JoePobega Have you indented the code yet?

**Comment by JosephPobega** [comment]
I FINALLY FIXED THE PROBLEM

**Comment by JosephPobega** [comment]
I FINALLY FIXED THE PROBLEM

**Comment by JosephPobega** [comment]
I FINALLY FIXED THE PROBLEM

**Comment by Pobega** [comment]
There's nothing here lol

**Comment by JosephPobega** [comment]
holy shit I totally forgot about my coding lessons!











                  dearly sorry Professor Pobega...


BUT I WILL GET BACK INTO CODING LESSONS VERY VERY SOON

**Comment by Pobega** [comment]
lol ok

**Comment by Pobega** [comment]
Unassigning myself and closing this because the work was never done.

**Pull request closed without merging**
